### PR TITLE
Do not depend on minitest-bonus-assertions

### PR DESCRIPTION
**Pull request by lucaskanashiro**
`minitest-bonus-assertions` is not available in Debian nor Ubuntu, and it can be easily removed as a test dependency (avoiding the necessity of creating a new package in those distributions to run tests).

- - -
This change is [Reviewable](https://reviewable.io/reviews/mime-types/ruby-mime-types/168)

### CODE REVIEW

**Comment by halostatue** [comment]
Honestly, I’m not inclined to accept this change. I added `minitest-bonus-assertions` because it let me write more expressive tests. I do not think that the changes made to remove this *improve* the tests in any way.

I understand the reason for your request here, but the package manager for Ruby is Rubygems (and to a lesser degree, bundler).

**Comment by lucaskanashiro** [comment]
Thanks for taking a look at this PR @halostatue , appreciated!

> Honestly, I’m not inclined to accept this change. I added `minitest-bonus-assertions` because it let me write more expressive tests. I do not think that the changes made to remove this _improve_ the tests in any way.

I agree it does not improve the tests but I also think it does not make it worse than it is. If you think that `assert_has_key` keyword is more meaningful, we could create a function with this name in a test helper file and implement this simple logic there, keeping the same method signature.

IMHO, from a software engineering perspective, we should introduce a new dependency when it is really needed, otherwise we are introducing new external code dependency which can bring some bugs with it as well at some point. The usage of `minitest-bonus-assetions` is minimal (you can see the simple changes I am proposing) and, at least from what has been used in the code, its implementation is quite straightforward (switching to `assert_includes` is easy) which wouldn't justify a new dependency IMHO. Sometimes is easier to simple add a new dependency, especially when we have a good package manager like in the ruby ecosystem, but I believe reducing the number of dependencies is always a good thing for future maintainability.
 
> I understand the reason for your request here, but the package manager for Ruby is Rubygems (and to a lesser degree, bundler).

Fair enough. I hope my argument above is at least useful.

**Comment by halostatue** [comment]
> > Honestly, I’m not inclined to accept this change. I added `minitest-bonus-assertions` because it let me write more expressive tests. I do not think that the changes made to remove this _improve_ the tests in any way.
> 
> I agree it does not improve the tests but I also think it does not make it worse than it is. If you think that `assert_has_key` keyword is more meaningful, we could create a function with this name in a test helper file and implement this simple logic there, keeping the same method signature.
>
> IMHO, from a software engineering perspective, we should introduce a new dependency when it is really needed, otherwise we are introducing new external code dependency which can bring some bugs with it as well at some point. The usage of `minitest-bonus-assetions` is minimal (you can see the simple changes I am proposing) and, at least from what has been used in the code, its implementation is quite straightforward (switching to `assert_includes` is easy) which wouldn't justify a new dependency IMHO. Sometimes is easier to simple add a new dependency, especially when we have a good package manager like in the ruby ecosystem, but I believe reducing the number of dependencies is always a good thing for future maintainability.

Or one adds a dependency that has it because you find yourself writing the same assertion helper again and again and again. That’s why I started looking for this *and* why I eventually forked `minitest-extra-assertions` as [`minitest-bonus-assertions`](https://github.com/halostatue/minitest-bonus-assertions). This is part of the reason that I consider the removal of `minitest-bonus-assertions` a *step backwards*. A lot of people laugh at the left-pad incident in the node community, but if you had to reimplement left-pad behaviour in every project in which you needed it, you’d start wishing for a package to help you PDQ. In *many* cases I have found value in saying that "a hash must have *all* these values" and find that a single line of `assert_has_keys` or `assert_missing_keys` (does *not* have any of these values) to be far more readable. The implementation is complex enough that you don’t want to copy it from project to project and have it possibly drift.

Given that `minitest-bonus-assertions` last needed modification five years ago, I think that it’s safe to say that it’s a stable clean library. Given that I’m the package owner and maintainer, I think it’s *really* safe to say that any issues with it would show themselves pretty quickly.

> > I understand the reason for your request here, but the package manager for Ruby is Rubygems (and to a lesser degree, bundler).
> 
> Fair enough. I hope my argument above is at least useful.

I don’t know how Debian / Ubuntu gem packaging is done (and, aside from the bit of work that I did to ensure that OS maintainers could set the MIME::Types data path, I don’t have any interest in it—I package Ruby applications with Bundler and libraries with `hoe`), but it would seem to me that the tests should be able to run in a packaging sandbox where a simple `gem install` can be done (this is sort of what `GEM_HOME` is for) and then for the final packaging, you just make sure that the packaging sandbox doesn’t have anything you don’t want.

**Comment by halostatue** [comment]
> OK. I see you are confident on the current implementation. Feel free to keep it like this, for now I am applying the proposed patch in Debian and therefore Ubuntu (and most of derivative distributions by consequence).

I find this disappointing, but understandable. I think that a *better* patch for you to apply is to lift the `assert_has_keys` method from `minitest-bonus-assertions` and put it into the test helper as you suggested. That way, if the tests change or need to change for any reason in the future, you have a *minimal* patch instead of this current *maximal* patch.

**Pull request closed without merging**
